### ISSUE TITLE
Understanding of definition of an item in the paper in the context of the datasets being used.

### ISSUE THREAD

**Issue by AmanSavaria1402** [TheophileBERTELOOT/ARM-AE#2]
Hi,
Im having confusion on what is the definiton of an item in here. Is it that each row in the dataset, is considered an item? or each column in a row is an item.
Apologies if it seems like a silly/trvial question but im having some gaps in understanding when i try to go through the code.
Thank you

**Comment by TheophileBERTELOOT** [comment]
i think the term item come from the retail field and it stayed.
It comes from transaction dataset that looked like that : 
1; bubble-gum; beer ; diapers
2; shampoo; beer; toothbrush; toothpaste
...
where each row is a transaction made by a customer.
The dataset that i used are not transaction dataset, but in order to execute some algorithm, i need a binary matrix, where each column is the presence or absence of an item, it would look like this : 
/; bubble-gum; beer; diapers; shampoo; toothbrush; toothpaste
1;1,1,1,0,0,0
2;0,1,0,1,1,1

With the classic tabular dataset that i used, i juste took every value possible in each column and build a binary column where 1 means the presence of this value and 0 the absence, and for continue data i used bins. Ex : 
Original dataset : 
/;Color;size
1;blue;10
2;red;2
3;green;55

The version i'll used is : 
/Blue;Red;Green;<10;10<50:>50
1;1,0,0,0,1,0
2;0,1,0,1,0,0
3;0,0,1,0,0,1

It's named an item but it's a possible value of a column in the original dataset. 
So each column is an item. I'm sorry if my answer i answer is confusing, i hope it answer to your question.

**Comment by AmanSavaria1402** [comment]
Thank You so very much for the explanation. I understood it perfectly.
So that means you can very well use a transaction binary dataset and train the model on that, is my understanding correct?
